---
apiVersion: extensions/v1beta1
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
kind: Deployment
metadata:
  name: hello-world-deployment-v3
  labels:
    demo: rollback-demo
# number of PHP pods (replicas) to run
# increase this number if you need to scale PHP horizontally
# since we have 3, the LoadBalancer will serve our app from all 3
spec:
  replicas: 2
  # The number of old deployments you want to keep around
  revisionHistoryLimit: 2
  # make replicas of kubernetes objects with the label app: php-dbconnect
  selector:
    matchLabels:
      app: hello-world-v3
  # the pod template describes what type of pod to create
  # when the defined number of replicas are not up
  # in this case, the pod that will be created is the one labeled app: php-dbconnect
  template:
    metadata:
      name: hello-world-pod-v3
      labels:
        app: hello-world-v3
        demo: rollback-demo

    spec:
      containers:
      - name: webapp
        image: training/webapp
        ports:
        - containerPort: 5000
