apiVersion: v1
kind: Pod
metadata:
  name: "aws-secret-demo"
spec:
  containers:
   - name: mypod
     image: "nginx"
     volumeMounts:
       - name: myawssecret
         mountPath: "/etc/myawscreds"
         readOnly: true
  volumes:
    - name: myawssecret
      secret:
        secretName: "my-aws-credentials"
