apiVersion: v1
kind: Pod
metadata:
  name: "redis-secret-demo-v2"
spec:
  containers:
   - name: mypod
     image: "redis"
     volumeMounts:
       - name: mysecret
         mountPath: "/etc/mycreds"
         readOnly: true
  volumes:
    - name: mysecret
      secret:
        secretName: "my-db-reds-v2"
