apiVersion: v1
# https://kubernetes.io/docs/concepts/configuration/secret/
kind: Secret
# Other Kubernetes objects in the cluster can reference values from our Secret
# using name: mysql-credentials and key: <somekey>, like key: user
metadata:
  name: my-aws-credentials
  labels:
    "heptio.com/example": lamp
type: Opaque
# Encode secrets exactly like this from your command line
# if you use a different command, you will run into errors with newlines
data:
  # root password for MySQL
  # the actual password is varMyRootPass
  # echo -n varMyRootPass | base64
  aws_access_key: bXl1c2VybmFtZQ==
  # user for MySQL
  # the actual username is varMyDBUser
  # echo -n varMyDBUser | base64
  aws_secret_access_key: ZHNkc3Jkc2Q=

